### ISSUE TITLE
No module named deprecation_wrapper

### ISSUE THREAD

**Issue by XinnuoXu** [PolyAI-LDN/conversational-datasets#71]
Hi Matthew, I met this problem when I was running:

python reddit/create_data.py   --output_dir ${DATADIR?}   --reddit_table ${PROJECT?}:${DATASET?}.${TABLE?}   --runner DataflowRunner   --temp_location ${DATADIR?}/temp   --staging_location ${DATADIR?}/staging   --project ${PROJECT?}   --dataset_format JSON --noauth_local_webserver

I1026 01:39:37.442483 139859749066496 dataflow_runner.py:177] 2020-10-26T01:39:37.193Z: JOB_MESSAGE_ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 766, in run
    self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 482, in _load_main_session
    pickler.load_session(session_file)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 254, in load_session
    return dill.load_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 363, in load_session
    module = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 423, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named deprecation_wrapper

**Comment by matthen** [comment]
Maybe this is related to https://github.com/tensorflow/tensorflow/issues/27079 ?

**Comment by XinnuoXu** [comment]
Hi Matthew, many thanks for your reply. I think it's a bit different from the #27079. However, I just solved it with Tensorflow==1.5.0. So far the code is running okay -ish.
